language: c

os:
  - linux

before_script:
  - git submodule update --init --recursive
  - git submodule update --recursive
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - make test

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
