language: c

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

sudo: required
dist: trusty

env:
  - BUILD_TYPE=tiny
  - BUILD_TYPE=regular-asm

os:
  - linux
  # - osx

before_install:
  - git submodule update --init --recursive
  - git submodule update --recursive

script:
  - WITHOUT_AMALG=1 make ${BUILD_TYPE}
  - make test

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/90c4eb53cc2fa148a058
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
