configuration: Release

environment:
  matrix:
    - BUILD_TYPE: tiny
    - BUILD_TYPE: large

matrix:
  fast_finish: true

build_script:
 - git submodule update --init --recursive
 - make.bat %BUILD_TYPE%

test_script:
 - make.bat test

artifacts:
 - path: luvi.exe

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
